### ISSUE TITLE
One last feed ...

### ISSUE THREAD

**Issue by JulianKahnert** [Janwillhaus/Podcast-Archiver#6] opened 2015-04-29 20:21 UTC
This feed `http://241568.website.snafu.de/wordpress/?cat=4&feed=rss2` returns the following error:
```
juka@Server:~$ python3 /home/juka/Podcast-Archiver/podcast_archiver.py -d /mnt/PLEX/Podcasts -s -f http://241568.website.snafu.de/wordpress/?cat=4&feed=rss2
[1] 21900
juka@Server:~$ 
Downloading archive for: http://241568.website.snafu.de/wordpress/?cat=4
1. Gathering link list ...Traceback (most recent call last):
  File "/home/juka/Podcast-Archiver/podcast_archiver.py", line 233, in <module>
    main()
  File "/home/juka/Podcast-Archiver/podcast_archiver.py", line 87, in main
    download_archive(feed)
  File "/home/juka/Podcast-Archiver/podcast_archiver.py", line 116, in download_archive
    subdir = feedobj['feed']['title']
  File "/usr/local/lib/python3.4/dist-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'title'
```

...sorry for spamming!

**Comment by Janwillhaus** [comment] 2015-10-29 12:13
I was not able to reproduce the error, the feed you provided actually downloads jus fine here. Given the time that past since the ticket was opened, I am closing this for now. Feel free to re-open the issue if the feed still doesn't work for you, and we'll dig further into the problem.

**Closed by Janwillhaus** 2015-10-29 12:13 UTC
